<?php 

$auto_usate = [
    [
        "id" => 1,
        "marca" => "peugeot",
        "carburante" => "super 95",
        "modello" => "208",
        "anno" => 2013,
        "cilindrata" => 1199,
        "trasmissione" => "manuale",
        "km" => 121055,
        "colore" => "nero",
        "prezzo" => 5890.00,
        "accessori" => "alzacristalli elettrici, climatizzatore, cruise control, vetri oscurati, tetto panoramico",
        "nPorte" => 5,
        "localita" => "torino",
        "trazione" => "null",
        "targa" => "null",
        "immagine" => "url peugeot"   
    ],
    [
        "id" => 2,
        "marca" => "bmw",
        "carburante" => "diesel",
        "modello" => "120",
        "anno" => 2010,
        "cilindrata" => 1995,
        "trasmissione" => "semiautomatico",
        "km" => 85000,
        "colore" => "blu",
        "prezzo" => 22.000,
        "accessori" => "null",
        "nPorte" => 5,
        "localita" => "roma",
        "trazione" => "anteriore",
        "targa" => "ab123gv",
        "immagine" => "url bmw"   
    ],
    [
        "id" => 3,
        "marca" => "fiat",
        "carburante" => "benzina",
        "modello" => "500",
        "anno" => 2010,
        "cilindrata" => 1242,
        "trasmissione" => "manuale",
        "km" => 98000,
        "colore" => "grigio",
        "prezzo" => 5990.00,
        "accessori" => "alzacristalli elettrici, climatizzatore, cruise control",
        "nPorte" => 3,
        "localita" => "roma",
        "trazione" => "posteriore",
        "targa" => "null",
        "immagine" => "url fiat"   
    ],
    [
        "id" => 4,
        "marca" => "ford",
        "carburante" => "benzina 91",
        "modello" => "ecosport",
        "anno" => 2018,
        "cilindrata" => 998,
        "trasmissione" => "manuale",
        "km" => 35383,
        "colore" => "bianca",
        "prezzo" => 16900.00,
        "accessori" => "null",
        "nPorte" => 5,
        "localita" => "cagliari",
        "trazione" => "null",
        "targa" => "ab123vg",
        "immagine" => "url ford"   
    ],
    [
        "id" => 5,
        "marca" => "ford",
        "carburante" => "benzina",
        "modello" => "mustang",
        "anno" => 2016,
        "cilindrata" => 2261,
        "trasmissione" => "automatico",
        "km" => 101000,
        "colore" => "rosso",
        "prezzo" => 24000.00,
        "accessori" => "alzacristalli elettrici, climatizzatore, cruise control, vetri oscurati, tetto panoramico",
        "nPorte" => 2,
        "localita" => "palermo",
        "trazione" => "anteriore",
        "targa" => "sd345gi",
        "immagine" => "url mustang"   
    ],
    [
        "id" => 6,
        "marca" => "vw",
        "carburante" => "diesel",
        "modello" => "polo",
        "anno" => 2008,
        "cilindrata" => 1896,
        "trasmissione" => "manuale",
        "km" => 230000,
        "colore" => "nero",
        "prezzo" => 3500.00,
        "accessori" => "alzacristalli elettrici, climatizzatore, cruise control, vetri oscurati, tetto panoramico",
        "nPorte" => 3,
        "localita" => "padova",
        "trazione" => "null",
        "targa" => "ag378ik",
        "immagine" => "url vw"   
    ],
]

?>